version: "3.5"

networks:

  rustynail:
    driver: bridge

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    networks:
    - rustynail
    ports:
    - "5432:5432"
    volumes:
    - ./postgresql:/var/lib/postgresql
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  rustynail:
    container_name: rustynail
    hostname: rustynail
    build: .
    image: ianblenke/rustynail
    networks:
    - rustynail
    ports:
    - "3030:3030"
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    depends_on:
    - postgres

